### ISSUE TITLE
Confirm methylkit code aligns with paper

### ISSUE THREAD

**Issue by sr320** [epigeneticstoocean/paper-gonad-meth#2]
https://github.com/epigeneticstoocean/paper-gonad-meth/tree/master/code

**Comment by yaaminiv** [comment]
Cloned the repo and made some changes. Unable to push these changes or create a pull request...

**Comment by sr320** [comment]
check now.

**Comment by sr320** [comment]
Should not need create pull request but rather you should have direct access - let me know if not

**Comment by yaaminiv** [comment]
Now have direct access.

[Cleaned up code](https://github.com/epigeneticstoocean/paper-gonad-meth/blob/master/code/03-methylkit.Rmd) and added sequence number to the script.
