### ISSUE TITLE
Add code for identifying transposable elements

### ISSUE THREAD

**Issue by sr320** [epigeneticstoocean/paper-gonad-meth#3]
@ https://github.com/epigeneticstoocean/paper-gonad-meth/tree/master/code

**Comment by kubu4** [comment]
I have this in a Jupyter notebook. Do you want me to pare it down to a more re-usable bash script?

**Comment by sr320** [comment]
yes please - something that is quasi implementable by reviewer.

**Comment by kubu4** [comment]
https://github.com/epigeneticstoocean/paper-gonad-meth/blob/master/code/te_repeatmasker.sh
