### ISSUE TITLE
Add README to code

### ISSUE THREAD

**Issue by DrK-Lo** [epigeneticstoocean/paper-gonad-meth#4]
It would be good to add a README to the code for us with a short description of each file in the order they are run. Thanks!

**Comment by yaaminiv** [comment]
Updated the [README](https://github.com/epigeneticstoocean/paper-gonad-meth/blob/master/code/readme.md)!

**Comment by sr320** [comment]
not completely.

**Comment by yaaminiv** [comment]
Updated: https://github.com/epigeneticstoocean/paper-gonad-meth/blob/master/code/README.md
