### ISSUE TITLE
GO-MWU for methylation data

### ISSUE THREAD

**Issue by yaaminiv** [epigeneticstoocean/paper-gonad-meth#5]
Looking at [GO-MWU](https://github.com/z0on/GO_MWU), I need to assign a "measure of significance":

> The table of significance measures: it is the comma-separated (CSV) table of continuous measures that must be associated with GO enrichment (for example, kME value, p-value, or dN/dS value). The table should have a header line, but what is in it is irrelevant. The first column should contain the gene name, and the second - the measure of interest

I don't have these values...do you think I could use methylation difference between treatment and control?

**Comment by sr320** [comment]
see also 
>table of measure of interest for your sequences: two columns of comma-separated values: gene id, continuous measure of significance such as log(fold-change) or -log(p-value). To perform standard GO enrichment analysis based on Fisher's exact test, use binary measure (1 or 0, i.e., either sgnificant or not). To analyze modules derived from WGCNA, specify 0 for genes not included in the module and the kME value (number between 0 and 1, module membership score) for genes included in the module.

you could use binary?

**Comment by sr320** [comment]
Also you have p-values.. so that would probably be the best to use

**Comment by yaaminiv** [comment]
@sr320 I have p-values related to DML significance, not necessarily gene significance. There are also some genes with multiple DML, so multiple p-values. I think I need one gene, one p-value

**Comment by yaaminiv** [comment]
Could use binary (gene has sig DML, gene doesn't have sig DML)

**Comment by sr320** [comment]
Yep - try binary.

**Comment by DrK-Lo** [comment]
The method is designed to be used with a continuous (not binary) variable, so you could try binary but you may get some weird behavior. I have some thoughts on how we may be able to get around that, will chat next meeting.
