### ISSUE TITLE
share plots

### ISSUE THREAD

**Issue by DrK-Lo** [epigeneticstoocean/paper-gonad-meth#6]
Hi Yaamini,

We're going through https://github.com/epigeneticstoocean/paper-gonad-meth/blob/master/code/04-methylkit.Rmd and was wondering if you could upload or share your plots from this script with us? We'd like to compare to Alan's results. thanks!

Katie

**Comment by yaaminiv** [comment]
@DrK-Lo haven't updated the plots yet in this repo, but you can find some of the plots to compare [in this folder](https://github.com/fish546-2018/yaamini-virginica/tree/master/analyses/2018-10-25-MethylKit/2018-10-25-Loci-Analysis). I'll let you know once the repo is updated.

**Comment by sr320** [comment]
@yaaminiv updated?

**Comment by yaaminiv** [comment]
Plots from this script are in [this folder](https://github.com/epigeneticstoocean/paper-gonad-meth/tree/master/analyses/2018-10-25-MethylKit). The percent CpG coverage and methylation plots are in [this folder](https://github.com/epigeneticstoocean/paper-gonad-meth/tree/master/analyses/2018-10-25-MethylKit/2018-10-25-Loci-Analysis).

**Comment by yaaminiv** [comment]
I also added links to each figure's pdf and code in the main README: https://github.com/epigeneticstoocean/paper-gonad-meth/blob/master/README.md
