### ISSUE TITLE
Analysis folder needs attention

### ISSUE THREAD

**Issue by sr320** [epigeneticstoocean/paper-gonad-meth#8]
quite a bit of files. 
likely not all directly needed to reproduce paper?

**Comment by yaaminiv** [comment]
No, not all are directly needed. Should I not include other files and analyses, or should I just link to the relevant files in the readme?

**Comment by yaaminiv** [comment]
I removed all extraneous files that are not pertinent to the analyses described in the paper. I also [updated the README](https://github.com/epigeneticstoocean/paper-gonad-meth/blob/master/analyses/README.md) with links to relevant files.
